### PR TITLE
Fix erroneous audio readbacks in runAltitude

### LINKED ISSUE #240: Improper Altitude Readbacks
See zlsa#769.

### PR DESCRIPTION
**Pull request by erikquinn**
Fixes #240.

### CODE REVIEW

File: src/assets/scripts/aircraft/AircraftInstanceModel.js [hunk 1]
```diff
@@ -904,12 +903,15 @@ export default class Aircraft {
...
         }
 
+        const newAltitude = this.fms.altitudeForCurrentWaypoint();
+        const radioTrendAltitude = radio_trend('altitude', this.altitude, newAltitude);
+        const currentWaypointRadioAltitude = radio_altitude(newAltitude);
         const readback = {
-            log: `${radioTrendAltitude} ${this.fms.altitudeForCurrentWaypoint()} ${isExpeditingString}`,
-            say: `${radioTrendAltitude} ${currentWaypointRadioAltitude} ${isExpeditingString}`
+            log: `${radioTrendAltitude} ${newAltitude}${isExpeditingString}`,
+            say: `${radioTrendAltitude} ${currentWaypointRadioAltitude}${isExpeditingString}`
```
Comment (n8rzz) [inline src/assets/scripts/aircraft/AircraftInstanceModel.js]: I would prefer that `isExpeditingString` not have the space and that any spacing would happen here within the template string itself.  Is there a reason you added it back in to `isExpeditingString` variable?

File: src/assets/scripts/aircraft/AircraftInstanceModel.js [hunk 2]
```diff
@@ -904,12 +903,15 @@ export default class Aircraft {
 
         let isExpeditingString = '';
         if (expedite) {
-            isExpeditingString = 'and expedite';
+            isExpeditingString = ' and expedite';
```
Comment (n8rzz) [inline src/assets/scripts/aircraft/AircraftInstanceModel.js]: I don't like these leading spaces within template string variables.  It makes it challenging to use later on.  It's better to do the spacing inside a template string itself then from within a variable.

```javascript
// not preferred
${radioTrendAltitude} ${currentWaypointRadioAltitude}${isExpeditingString}

// preferred
${radioTrendAltitude} ${currentWaypointRadioAltitude} ${isExpeditingString}
```

The good example reads like a sentence would. the vars themselves don't contain spaces because that is accomplished within the string itself.  The vars behave predictably and could be rearranged without worry of hidden spacing.  That isn't so easy to do with the other example.

File: src/assets/scripts/aircraft/AircraftInstanceModel.js [hunk 3]
```diff
@@ -873,13 +873,12 @@ export default class Aircraft {
         const altitude = data[0];
         let expedite = data[1];
         const airport = window.airportController.airport_get();
-        const radioTrendAltitude = radio_trend('altitude', this.altitude, this.fms.altitudeForCurrentWaypoint());
-        const currentWaypointRadioAltitude = radio_altitude(this.fms.altitudeForCurrentWaypoint());
```
Comment (n8rzz) [inline src/assets/scripts/aircraft/AircraftInstanceModel.js:877]: after #181 is merged, this type of thing will be handled better.

When I moved this to the top of the method, I was under the assumption that the `alititudeForCurrentWaypoint` would remain the same through the execution of this entire method.  I can see, on line 898, that is not the case.  grrr!

In the future this `runAltitude` method will likely be split up into many smaller methods.

**Review by n8rzz — CHANGES_REQUESTED** [review]
My only question is on the template strings.  

Is there a reason you added the space back into the var?  I'd prefer to keep the spaces inside actual template strings instead of within the vars themselves.

But, if there is a good reason, be sure to add a comment about the why.

File: src/assets/scripts/aircraft/AircraftInstanceModel.js (hunk 2 above)
Comment (erikquinn) [reply src/assets/scripts/aircraft/AircraftInstanceModel.js]: I understand. Trouble is that `isExpeditedString` may or may not contain a value. If it is an empty string, then the template string would have a trailing space... hence the addition of the space in the expedite string. If it's present, it will be spaced properly, and if not, it will end at the altitude.

Perhaps it's better to build the string as you've described and run `.trim()` on it?

**Comment by erikquinn** [comment]
Changelog entry added here as well.

File: src/assets/scripts/aircraft/AircraftInstanceModel.js (hunk 2 above)
Comment (n8rzz) [reply src/assets/scripts/aircraft/AircraftInstanceModel.js]: Yeah, I thought that would be the case here.  Does the extra space at the end actually affect how its displayed in the ui?  I'd rather not have `trim` in there, though that is an option.

I'd rather leave it as-is and just have you add a comment (pretty much what you said above).

Comment (erikquinn) [reply src/assets/scripts/aircraft/AircraftInstanceModel.js]: Yeah, the trailing space would cause more `"AAL123, descend and maintain 5000 , turn right heading 270" spacing issues.

That sounds good though, I'll get that done sometime later today.

File: src/assets/scripts/aircraft/AircraftInstanceModel.js (hunk 1 above)
Comment (n8rzz) [reply src/assets/scripts/aircraft/AircraftInstanceModel.js]: @erikquinn here is another possible solution, it adds a little more code.  But I think it's cleaner. you could always just build the base string with `${radioTrendAltitude} ${currentWaypointRadioAltitude}` and the other one before the `if (expedite)` block and simply overwrite that string when expedite is true?
```javascript
const radioTrendWithAltitude = `${radioTrendAltitude} ${newAltitude}`;
const readback = {
    log: radioTrendWithAltitude
}

if (expedite) {
    readback.log = `${radioTrendWithAltitude} and expedite`;
}
```
_obviously this is an abbreviated example. I'm sure you can see where I'm going with this_

Comment (erikquinn) [reply src/assets/scripts/aircraft/AircraftInstanceModel.js]: I like this more. :+1:

File: src/assets/scripts/aircraft/AircraftInstanceModel.js (hunk 2 above)
Comment (erikquinn) [reply src/assets/scripts/aircraft/AircraftInstanceModel.js]: Fixed via your later suggestion below.

File: src/assets/scripts/aircraft/AircraftInstanceModel.js (hunk 1 above)
Comment (erikquinn) [reply src/assets/scripts/aircraft/AircraftInstanceModel.js]: Fixed via something similar to the described.

File: src/assets/scripts/aircraft/AircraftInstanceModel.js [hunk 4]
```diff
@@ -902,16 +901,21 @@ export default class Aircraft {
...
+        const newAltitude = this.fms.altitudeForCurrentWaypoint();
+        const instruction = radio_trend('altitude', this.altitude, newAltitude);
+        const readback_text = `${instruction} ${newAltitude}`;
+        const readback_verbal = `${instruction} ${radio_altitude(newAltitude)}`;
 
         const readback = {
-            log: `${radioTrendAltitude} ${this.fms.altitudeForCurrentWaypoint()} ${isExpeditingString}`,
-            say: `${radioTrendAltitude} ${currentWaypointRadioAltitude} ${isExpeditingString}`
+            log: `${readback_text}`,
+            say: `${readback_verbal}`
```
Comment (n8rzz) [inline src/assets/scripts/aircraft/AircraftInstanceModel.js]: because the original is a template string, all thats needed here is just the var.
```javascript
// instead of
log: `${readback_text}`,
say: `${readback_verbal}`

// all you need is
log: readback_text,
say: readback_verbal
```

File: src/assets/scripts/aircraft/AircraftInstanceModel.js [hunk 5]
```diff
@@ -902,16 +901,21 @@ export default class Aircraft {
...
         };
 
+        if (expedite) {
+            readback.log = `${readback_text} and expedite`;
+            readback.say = `${readback_verbal} and expedite`;
```
Comment (n8rzz) [inline src/assets/scripts/aircraft/AircraftInstanceModel.js:916]: here, though, you _do_ need to use template strings. 

👍 this looks so much nicer.

**Review by n8rzz — CHANGES_REQUESTED** [review]
Just one little syntax thing and this is good to go!  Nice work!!

File: src/assets/scripts/aircraft/AircraftInstanceModel.js (hunk 4 above)
Comment (erikquinn) [reply src/assets/scripts/aircraft/AircraftInstanceModel.js]: LOL I forgot I had already pulled everything else out of there. :unamused: Good call!

Comment (erikquinn) [reply src/assets/scripts/aircraft/AircraftInstanceModel.js]: Fixed. :+1:

**Review by n8rzz — APPROVED** [review]
:shipit:
