### PR TITLE
bugfix/ATC-6

### LINKED ISSUE #6: Airports with negative elevation cause funkiness with Aircraft
Example airport: `EHAM`

With a fix in place for #5, a new issue has presented itself.  When the airport is first loaded all the departures crash due to terrain collisions.  Additionally, any new departures spawn directly on a runway and are in the process of taking off as though they have already been cleared.

I suspect that this has something to do with the `AircraftInstanceModel` defaulting the altitude to 0 and only setting an altitude, in the `parse` method if one is passed in.  I was playing with something like this:

``` javascript
parse(data) {
    this.altitude = _get(data, 'altitude', window.airportController.airport.current.elevation);

    if (this.altitude !== 0) {
        this.fms.setCurrent({ altitude: this.altitude });
    }
}
```

But this is a rather short-sided solution.  It solves this problem but creates new ones.  I need to dig into how altitude, elevation and the Aircraft are all working together in order for me to get this one fixed properly.

### PR DESCRIPTION
**Pull request by erikquinn**
Resolves #6.

Airports using negative elevations now behave properly.

### CODE REVIEW

**Comment by erikquinn** [comment]
@n8rzz On an unrelated note, if you're using zube with this, could you add me to the board? I've loved using it previously for my own planning and prioritization, and think it would be a good way to collaborate.

**Comment by n8rzz** [comment]
invite sent!

I have an active sprint (Sprint 1) going for current v3.0.x features and additional v3.0.0 bugfixes.  I'm doing 4 week sprints just to spread out the tasks and not make myself feel too rushed.  

Take a look and feel free to make changes.  Also, let me know if you have any issues

**Comment by n8rzz** [comment]
made you an admin as well :-)

File: src/assets/scripts/aircraft/AircraftInstanceModel.js [hunk 1]
```diff
@@ -2707,4 +2686,17 @@ export default class Aircraft {
...
+     * Aircraft has "weight-on-wheels" (on the ground)
+     * @for AircraftInstanceModel
+     * @method wow
+     */
+    wow() {
+        const error_allowance = 5;
+        const apt = window.airportController.airport_get();
+        const rwy_elev = apt.getRunway(this.rwy_dep || this.rwy_arr).elevation;
+        const apt_elev = apt.position.elevation;
+        return this.altitude - (rwy_elev || apt_elev) < error_allowance;
```
Comment (n8rzz) [inline src/assets/scripts/aircraft/AircraftInstanceModel.js:2700]: I have a few notes here:
- if a function/method returns a boolean, it should be named with an `is` at the beginning.  so in this case the method should be named `isWow`.  This way, you can tell at a glance that a function/method will return a boolean without having to look it up.  Kind of like with ruby where boolean functions should have a `?` at the end.
- variable names should be spelled out (const/let) and should also be camel case.  it makes it clear for a new developer to understand what is going on.  it also makes things easy to read.  in this case its pretty apparent, but I would prefer to see 

``` javascript
apt -> airport 
rwy_elevation -> runwayElevation
apt_elev -> airportElevation
```
- this line `apt.getRunway(this.rwy_dep || this.rwy_arr).elevation` and this line `return this.altitude - (rwy_elev || apt_elev) < error_allowance` concern me a little bit.  I'm not a fan of inline `||` like this because it's hard to read.  Ideally there would be a method in the `AirportModel` that could handle the logic of determining if a runway is an arrival or departure.  Then you could just ask for the runway elevation.  But that is for a future refactor.
- always include a space above a return statement.  this is another readability thing.  it just makes it easier to pick out and separates the assignments/logics in a method from the return.

---

I'm going to approve this as-is, because this file will probably get worked over pretty good in the near future and it does fix the glitch.

I hope I'm not being too harsh on these reviews.  If I am, please let me know and I'll dial it back.  I just want to make sure that we maintain good syntax across the project post v3.0.0.  A lot of the things that I do when I code have become habit, but I know that isn't the case for everybody.  I want to encourage not discourage and I know that constantly calling out syntax errors can be frustrating.  So I apologize in advance if it gets annoying.  It's for the greater good, I promise!

**Comment by n8rzz** [comment]
invite sent!

I have an active sprint (Sprint 1) going for current v3.0.x features and
additional v3.0.0 bugfixes.  I'm doing 4 week sprints just to spread out
the tasks and not make myself feel too rushed.

Take a look and feel free to make changes.  Also, let me know if you have
any issues

File: src/assets/scripts/aircraft/AircraftInstanceModel.js (hunk 1 above)
Comment (erikquinn) [reply src/assets/scripts/aircraft/AircraftInstanceModel.js:2700]: @n8rzz I come from an ATC background, where (basically) the only stuff worth discussing is how you should have worked your traffic differently, or done x/y/z better/faster/etc. So I appreciate the sentiment, but relative to what I work in, this is _far_ from the negativity I'm already used to anyway; so no, you haven't been "harsh" at all.

Regardless, I'm glad to get such thorough feedback, especially when you often provide explanations as to _why_ a particular change is needed. I've never been "set in my ways", and with each step, I'm coming to see why you've made each suggestion. Most important to me is improvements upon the sim, and it's getting cleaner and easier to work with every day, so you'll hear no complaints from this guy...

Comment (n8rzz) [reply src/assets/scripts/aircraft/AircraftInstanceModel.js:2700]: That makes me smile.

Everybody handles feedback differently, I'm glad to read that you both understand where it's coming from and that it is with an eye toward improvement.

As a developer I, too, receive feedback at work.  Much like the feedback I give you, actually.  However, in my line of work, lives aren't [usually] on the line.  

Most of the feedback I have given so far center around syntax inconsistencies and simplification of logic.  

Syntax is defined in the standards doc I've shared before (https://github.com/thenerdery/javascript-standards) and is just a matter of practice and experience.  Hooking up eslint and making sure it is working correctly will vastly improve syntax errors.  Its a great tool because it'll bark at you if you did it wrong.  It's made a _huge_ difference for me.  I swear by it!

Simplification of logic takes time, practice and experience.  I am certainly not an expert in this area, but I do know a few things that inform the direction we're headed in with `v3.0.x`.  In some ways it means thinking about the problem a little differently.

Testing is one way to do that.  You may have noticed in the `v3.0.x` features I'm working on, they also include tests.  I am a big proponent of TDD (https://en.wikipedia.org/wiki/Test-driven_development) when it makes sense.  For a large portion of this app, it does.  So I'm adding tests.  Making a new feature that is also testable requires thinking about the problem in a different way than just spewing out code.  One needs to think about _what_ that code is doing.  And also how it reacts to non-happy path circumstances.  It also provides a way to know when things break and is another form of documentation.  You can look through the tests and get a good idea of what is going on.
